require: rubocop-rspec

AllCops:
  DefaultFormatter: progress
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false
