inherit_from: .rubocop_todo.yml

require: rubocop-rspec

AllCops:
  DefaultFormatter: progress
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true

# Should I just disable these?
# Metrics/BlockLength
# Metrics/MethodLength
# Style/BracesAroundHashParameters
