version: 1.0.{build}-{branch}

cache:
  - vendor/bundle

install:
  - set PATH=C:\Ruby25-x64\bin;%PATH%
  - bundle install
  - choco install googlechrome
  - reg import bin\ie.reg
  - npm install -g appium

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - bundle exec rspec
