version: 1.0.{build}-{branch}

cache:
  - vendor/bundle

install:
  - set PATH=C:\Ruby25-x64\bin;%PATH%
  - bundle install
  - choco install googlechrome
  - reg import bin\ie.reg
  - npm install -g appium
  # Can't choco install WinAppDriver yet.
  # Also, am currently hardcoding version number. When there's a new Appium/
  # WinAppDriver pairing available this may break because the Appium will be
  # too new.
  - appveyor DownloadFile https://github.com/Microsoft/WinAppDriver/releases/download/v1.0/WindowsApplicationDriver.msi
  - msiexec /i WindowsApplicationDriver.msi /quiet /qn /norestart /log install.log
  # allow developer mode for non-UWP-stuffs including WinAppDriver
  - reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock" /t REG_DWORD /f /v "AllowDevelopmentWithoutDevLicense" /d "1"

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v
  - npm v appium
  - ver

test_script:
  - bundle exec rspec

artifacts:
  - path: install.log
    name: WAD installer log
